# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 15 Pro Max",
   "iPhone 14 Plus",
   "iPhone 15 Pro",
   "iPhone 14",
#   "iPhone 8 Plus",
#   "iPhone SE (3rd generation, 2nd generation)".
#   "iPhone SE (1st generation)",
#   "iPhone 4s",
   "iPad Pro 13-inch (M4)",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPad Pro 11-inch (M4)",
   "iPad (9th generation)",
   "iPad mini (6th generation)"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("Generate Screenshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(false)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

erase_simulator(true)
reinstall_app true

# For more information about all available options run
# fastlane action snapshot

output_simulator_logs true
headless true
number_of_retries 1
stop_after_first_error true
result_bundle true
concurrent_simulators true
